name: Scott Robertson
markdown: redcarpet
pygments: true
paginate: 5
paginate_path: "blog/:num"
assets:
  js_compressor:  yui
  css_compressor:  yui

exclude:
 - Gemfile
 - Procfile
 - vendor
 - gems
 - Gemfile.lock
